---
kind: pipeline
type: docker
name: default

node:
  k: y

clone:
  depth: 10

trigger:
  branch:
  - master #avoid double builds on PRs
  event:
  - push

steps:
  - name: build and push dm-buildimage
    image: plugins/docker
    privileged: true
    settings:
      repo: aurorastation/dm-buildimage
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BYOND_VERSION=513.1542
        - SPACEMANDMM_VERSION=suite-1.6
        - RUSTG_VERSION=0.4.2+a2
        - FLYWAY_VERSION=5.2.4

      tags: latest
      purge: false

---
kind: signature
hmac: 0b59e493962fcdec872f0699f67d1332efdd8785361cfb1b32dfaf7087961d63

...
