---
kind: pipeline
type: docker
name: default

node:
  k: y

clone:
  depth: 10

trigger:
  branch:
  - master #avoid double builds on PRs

steps:
  - name: build and push dm-buildimage
    image: plugins/docker
    privileged: true
    settings:
      repo: aurorastation/dm-buildimage
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BYOND_VERSION=513.1536
        - SPACEMANDMM_VERSION=suite-1.6
        - RUSTG_VERSION=0.4.2+a2
        - FLYWAY_VERSION=5.2.4

      tags: latest
      purge: false

---
kind: signature
hmac: 25bf0a1d79308cd6449714e544dc0f4d48356393329db2a727494db81a1e22b1

...
