---
kind: pipeline
type: docker
name: default

clone:
  depth: 10

trigger:
  branch:
  - master #avoid double builds on PRs

steps:
  - name: build and push dm-buildimage
    image: plugins/docker
    priviledged: true
    settings:
      repo: aurorastation/dm-buildimage
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BYOND_VERSION=513.1536
      tags: latest

---
kind: signature
hmac: b12b76fca7a07f800468d4ea14c73e4e979e140744b1b8e013237a021df6b697

...
