---
kind: pipeline
type: docker
name: default

clone:
  depth: 10

trigger:
  branch:
  - master #avoid double builds on PRs

steps:
  - name: build and push dm-buildimage
    image: plugins/docker
    settings:
      repo: aurorastation/dm-buildimage
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - BYOND_VERSION=513.1536
      tags: latest

---
kind: signature
hmac: 333501f29893b798f75437399c55502f2cd79882aa4db56e7cade384a0a35371

...
